name: Publish Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build jar
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/libs/manapart-mod-manager.jar,./app/mmm.desktop
      - name: Zip files
        run: zip -r mod-manager.zip build/libs/manapart-mod-manager.jar app/mmm.desktop
      - name: Upload mod to NexusMods
        id: upload
        uses: Nexus-Mods/upload-action@main
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          file_group_id: ${{ vars.NEXUSMODS_FILE_GROUP_ID }}
          filename: mod-manager.zip
          display_name: "Manapart Mod Manager"
          description: "CLI Mod Manager"
          version: ${{ github.event.release.tag_name || github.event.inputs.version ||  github.ref_name }}
